Lab06/01_ButterfliesShop_begin/ButterfliesShop/Models/Butterfly.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ButterfliesShop.Models
{
    public class Butterfly
    {
        public int Id { get; set; }
        [Display(Name = "Common Name:")]
        [Required(ErrorMessage = "Please enter the butterfly name")]
        public string CommonName { get; set; }
        [Display(Name = "Butterfly Family:")]
        [Required(ErrorMessage = "Please select the butterfly family")]
        public Family? ButterflyFamily { get; set; }
        [Display(Name = "Butterflies Quantity:")]
        [Required(ErrorMessage = "Please select the butterfly quantity")]
        public int? Quantity { get; set; }
        [Display(Name = "Characteristics")]
        [Required(ErrorMessage = "Please type the characteristics")]
        [MaxLength(50)]
        public string Characteristics { get; set; }
        [Display(Name = "Updated on:")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd / MM / yy}")]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Butterflies Picture:")]
        [Required(ErrorMessage = "Please select the butterflies picture")]
        public IFormFile PhotoAvatar { get; set; }
        public string ImageName { get; set; }
        public byte[]  PhotoFile { get; set; }
        public string ImageMimeType { get; set; }

    }
}

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Models/Family.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public enum Family
    {
        Grassland,
        Nymphalidae,
        Danaine,
        Riodinidae
    }
}

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Models/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ButterfliesShop.Models
{
    public class IndexViewModel
    {
        public List<Butterfly> Butterflies  { get; set; }
    }
}

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Controllers/ButterflyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ButterfliesShop.Models;
using ButterfliesShop.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.ApplicationInsights.AspNetCore.Extensions;
using System.Threading;

namespace ButterfliesShop.Controllers
{
    public class ButterflyController : Controller
    {
        private IDataService _data;
        private IHostingEnvironment _environment;
        private IButterfliesQuantityService _butterfliesQuantityService;

        public ButterflyController(IDataService data, IHostingEnvironment environment, IButterfliesQuantityService butterfliesQuantityService)
        {
            _data = data;
            _environment = environment;
            _butterfliesQuantityService = butterfliesQuantityService;
            InitializeButterfliesData();
        }

        public IActionResult Index()
        {
            IndexViewModel indexViewModel = new IndexViewModel();
            indexViewModel.Butterflies = _data.ButterfliesList;
            return View(indexViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Butterfly butterfly)
        {
            if (ModelState.IsValid == true)
            {
                Butterfly lastButterfly = _data.ButterfliesList.LastOrDefault();
                butterfly.CreatedDate = DateTime.Today;
                if (butterfly.PhotoAvatar != null && butterfly.PhotoAvatar.Length > 0)
                {
                    butterfly.ImageMimeType = butterfly.PhotoAvatar.ContentType;
                    butterfly.ImageName = Path.GetFileName(butterfly.PhotoAvatar.FileName);
                    butterfly.Id = lastButterfly.Id + 1;
                    _butterfliesQuantityService.AddButterfliesQuantityData(butterfly);
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        butterfly.PhotoAvatar.CopyTo(memoryStream);
                        butterfly.PhotoFile = memoryStream.ToArray();
                    }
                    _data.AddButterfly(butterfly);
                    if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                    {
                        Thread.Sleep(2000);
                        List<Butterfly> listButterfly = _data.ButterfliesList;
                        return PartialView("_IndexPartailview", listButterfly);
                    }
                        return RedirectToAction("Index");
                }
                return View(butterfly);
            }
            return View(butterfly);
        }
        private void InitializeButterfliesData()
        {
            if (_data.ButterfliesList == null)
            {
                List<Butterfly> butterflies = _data.ButterfliesInitializeData();
                foreach (var butterfly in butterflies)
                {
                    _butterfliesQuantityService.AddButterfliesQuantityData(butterfly);
                }
            }
        }

        public IActionResult GetImage(int id)
        {
            Butterfly requestedButterfly = _data.GetButterflyById(id);
            if (requestedButterfly != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = @"\images\";
                string fullPath = webRootpath + folderPath + requestedButterfly.ImageName;
                if (System.IO.File.Exists(fullPath) ==  true)
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedButterfly.ImageMimeType);
                }

                if (requestedButterfly.PhotoFile.Length > 0)
                {
                    return File(requestedButterfly.PhotoFile, requestedButterfly.ImageMimeType);
                } 
                return NotFound();
            }
            
            return NotFound();
            
        }
    }
}

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Views/Butterfly/Create.cshtml
@using ButterfliesShop.Models
@model ButterfliesShop.Models.Butterfly
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
</head>
<body>
    <div class="container">
        <h1 class="main-title">Add Butterflies to the Shop</h1>
        <div id="divloading"></div>

        <form asp-action="Create" method="post" data-ajax="true"
              data-ajax-method="POST"
              data-ajax-mode="replace"
              data-ajax-update="#content"
              data-ajax-loading="#divloading"
              data-ajax-success="Success"
              data-ajax-failure="Failure"
              enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div class="form-field">
                <label asp-for="CommonName"></label>
                <input asp-for="CommonName" />
                <span asp-validation-for="CommonName"> </span>
            </div>
            <div class="form-field">
                <label asp-for="ButterflyFamily"></label>
                <select asp-for="ButterflyFamily" asp-items="Html.GetEnumSelectList<Family>()">
                    <option selected="selected" value=""> Select </option>
                </select>
                <span asp-validation-for="ButterflyFamily"></span>
            </div>
            <div class="form-field">
                <label asp-for="Characteristics"></label>
                <TEXTAREA asp-for="Characteristics"></TEXTAREA>
                <span asp-validation-for="Characteristics"></span>
            </div>
            <div class="form-field">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" />
                <span asp-validation-for="Quantity"></span>
            </div>
            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" />
                <span asp-validation-for="PhotoAvatar"></span>
            </div>
            <div class="form-field">
                <input type="submit" value="Submit" />
            </div>
            
        </form>
    </div>
    <div id="content"></div>
</body>
</html>

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Views/Butterfly/Index.cshtml
@model ButterfliesShop.Models.IndexViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="~/css/butterflies-shop-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="main-title">Butterfiles Shop</h1>
        <p class="into">Welcome to our Web Store, Enjoy a Wide Variety of Butterflies</p>
        <p class="into">Our Butterflies in the Shop</p>
        <button type="button" onclick="location.href='@Url.Action("Create", "Butterfly")'"> Add Butterflies </button>
        <div class="img-container">
            @foreach (var item in Model.Butterflies)
            {
                <div class="photo-index-card">
                    <h3>@Html.DisplayFor(modelItem => item.CommonName)</h3>
                    @if (item.ImageName != null)
                    {
                        <div class="photo-display">
                            <img class="photo-display-img" src=@Url.Action("GetImage", "Butterfly", new { Id = item.Id }) alt="Alternate Text" />
                        </div>
                    }
                    <div>
                        <p class="display-label">@Html.DisplayNameFor(model => item.ButterflyFamily)</p>
                        <br />
                        <p class="display-field">@Html.DisplayFor(model => item.ButterflyFamily)</p>
                        <div class="display-info">
                            <p class="display-label">@Html.DisplayNameFor(modle => item.Characteristics)</p>
                            <p class="display-field"> @Html.DisplayFor(Model => item.Characteristics)</p>
                        </div>
                        <div>
                            <p class="display-label">@Html.DisplayNameFor(modle => item.Quantity)</p>
                            <p class="display-field"> @Html.DisplayFor(Model => item.Quantity)</p>
                        </div>
                        <div>
                            <p class="display-label">@Html.DisplayNameFor(modle => item.CreatedDate)</p>
                            <p class="display-field"> @Html.DisplayFor(Model => item.CreatedDate)</p>
                        </div>
                    </div>
                </div>
             }
        </div>
    </div>
</body>
</html>

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Views/Shared/_IndexPartailview.cshtml
@using ButterfliesShop.Models
@model List<Butterfly>
@{
    Layout = null;
}

@foreach (var item in Model)
{
<div class="photo-index-card">
    @if (item.ImageName != null)
    {
        <div class="photo-display">
            <img class="photo-display-img" src=@Url.Action("GetImage", "Butterfly", new { Id = item.Id }) alt="Alternate Text" />
        </div>
    }
    <h3>@Html.DisplayFor(modelItem => item.CommonName)</h3>
    <div>
        <p>@Html.DisplayNameFor(model => item.ButterflyFamily)</p>
        <br />
        <p>@Html.DisplayFor(model => item.ButterflyFamily)</p>
        <div>
            <p>@Html.DisplayNameFor(modle => item.Characteristics)</p>
            <p> @Html.DisplayFor(Model => item.Characteristics)</p>
        </div>
        <div>
            <p>@Html.DisplayNameFor(modle => item.Quantity)</p>
            <p> @Html.DisplayFor(Model => item.Quantity)</p>
        </div>
        <div>
            <p>@Html.DisplayNameFor(modle => item.CreatedDate)</p>
            <p> @Html.DisplayFor(Model => item.CreatedDate)</p>
        </div>
    </div>
</div>
}

Lab06/01_ButterfliesShop_begin/ButterfliesShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - My ASP.NET Application</title>

    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <script type="text/javascript" src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                     @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })              
            </div>
            <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/respond.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>